/**
 * app/layout.tsx PWA 모바일 메타 태그 검증 테스트
 *
 * Next.js App Router의 Metadata API 또는 직접 <meta> 태그를 통해
 * PWA에 필요한 모바일 메타 태그가 포함되어 있는지 검증합니다.
 *
 * 검증 항목:
 * - viewport 메타 태그
 * - theme-color 메타 태그
 * - apple-mobile-web-app-capable
 * - apple-mobile-web-app-status-bar-style
 * - apple-mobile-web-app-title
 * - manifest 링크 태그
 */

import fs from 'fs';
import path from 'path';

const ROOT = process.cwd();
const LAYOUT_PATH = path.join(ROOT, 'app', 'layout.tsx');

describe('app/layout.tsx PWA mobile meta tags', () => {
  let layoutContent: string;

  beforeAll(() => {
    layoutContent = fs.readFileSync(LAYOUT_PATH, 'utf-8');
  });

  // ----------------------------------------------------------------
  // manifest 링크 연결
  // ----------------------------------------------------------------
  describe('manifest link', () => {
    it('should reference manifest.json in metadata or <link> tag', () => {
      // Next.js Metadata API: manifest: '/manifest.json'
      // 또는 <link rel="manifest" href="/manifest.json" />
      expect(layoutContent).toMatch(/manifest.*manifest\.json|manifest\.json.*manifest/);
    });
  });

  // ----------------------------------------------------------------
  // viewport 설정
  // ----------------------------------------------------------------
  describe('viewport meta tag', () => {
    it('should define viewport configuration', () => {
      // Next.js 15 Metadata API: export const viewport = { ... }
      // 또는 metadata.viewport 또는 직접 <meta name="viewport" ... />
      expect(layoutContent).toMatch(
        /viewport|<meta[^>]+name=["']viewport["']/
      );
    });

    it('should include width=device-width in viewport', () => {
      expect(layoutContent).toContain('width=device-width');
    });

    it('should include initial-scale=1 in viewport', () => {
      expect(layoutContent).toContain('initial-scale=1');
    });
  });

  // ----------------------------------------------------------------
  // theme-color
  // ----------------------------------------------------------------
  describe('theme-color meta tag', () => {
    it('should define theme-color in metadata or <meta> tag', () => {
      // Next.js Metadata API: themeColor: '#...'
      // 또는 <meta name="theme-color" content="#..." />
      expect(layoutContent).toMatch(
        /themeColor|theme.color|theme_color|<meta[^>]+name=["']theme-color["']/
      );
    });
  });

  // ----------------------------------------------------------------
  // Apple PWA 메타 태그
  // ----------------------------------------------------------------
  describe('Apple PWA meta tags', () => {
    it('should include apple-mobile-web-app-capable configuration', () => {
      // Next.js Metadata API: appleWebApp: { capable: true }
      // 또는 <meta name="apple-mobile-web-app-capable" content="yes" />
      expect(layoutContent).toMatch(
        /appleWebApp|apple.mobile.web.app.capable|apple-mobile-web-app-capable/
      );
    });

    it('should include apple-mobile-web-app-status-bar-style', () => {
      expect(layoutContent).toMatch(
        /statusBarStyle|status.bar.style|apple-mobile-web-app-status-bar-style/
      );
    });

    it('should include apple-mobile-web-app-title', () => {
      expect(layoutContent).toMatch(
        /appleWebApp.*title|apple-mobile-web-app-title|apple.mobile.web.app.title/
      );
    });
  });

  // ----------------------------------------------------------------
  // Next.js Metadata API 구조 검증
  // ----------------------------------------------------------------
  describe('Next.js Metadata API structure', () => {
    it('should export metadata object or viewport export', () => {
      // export const metadata 또는 export const viewport
      expect(layoutContent).toMatch(/export\s+const\s+(?:metadata|viewport)/);
    });

    it('should have a meaningful app title (not default Next.js boilerplate)', () => {
      // "Create Next App" 기본값이 아닌 실제 앱 이름이어야 함
      expect(layoutContent).not.toContain('Create Next App');
    });

    it('should have a meaningful app description', () => {
      // "Generated by create next app" 기본값이 아닌 실제 설명이어야 함
      expect(layoutContent).not.toContain('Generated by create next app');
    });
  });

  // ----------------------------------------------------------------
  // 아이콘 설정
  // ----------------------------------------------------------------
  describe('icon configuration', () => {
    it('should define Apple touch icon', () => {
      // appleWebApp.startupImage 또는 icons.apple 또는 <link rel="apple-touch-icon" ... />
      expect(layoutContent).toMatch(
        /apple.touch.icon|appleWebApp|icons.*apple|apple.*icon/i
      );
    });
  });
});
